version: "3"
services:
  micronode-fe:
    container_name: microFrontend
    # network_mode: host
    build:
      context: "."
      dockerfile: "./micronode-fe/Dockerfile"
    ports: 
      - 80:80
    depends_on:
      - micronode-core
    volumes:
      - ./micronode-fe:/app

  micronode-core:
    network_mode: host
    build:
      context: "."
      dockerfile: "./micronode-core/Dockerfile"
    depends_on: 
      - micronode-company
      - micronode-user
      - micronode-event
    volumes: 
      - ./micronode-core:/opt/app

  micronode-company:
      network_mode: host
      build:
        context: "."
        dockerfile: "./micronode-company/Dockerfile"
      ports:
        - "7002:7002"
      volumes: 
        - ./micronode-company:/opt/app

  micronode-user:
    network_mode: host
    build:
      context: "."
      dockerfile: "./micronode-user/Dockerfile"
    volumes:
      - ./micronode-user:/opt/app

  micronode-event:
    network_mode: host
    build:
      context: "."
      dockerfile: "./micronode-event/Dockerfile"
    volumes:
      - ./micronode-event:/opt/app