version: "3"
services: 
  micronode-core:
    build:
      context: "."
      dockerfile: "./micronode-core/Dockerfile"
    ports:
      - "3001:3001"
    volumes: 
      - ./micronode-core:/opt/app

  micronode-company:
      build:
        context: "."
        dockerfile: "./micronode-company/Dockerfile"
      ports:
        - "3002:3002"
      volumes: 
        - ./micronode-company:/opt/app

  micronode-user:
    build:
      context: "."
      dockerfile: "./micronode-user/Dockerfile"
    ports:
      - "3003:3003"
    volumes: 
      - ./micronode-user:/opt/app

  micronode-event:
    build:
      context: "."
      dockerfile: "./micronode-event/Dockerfile"
    ports:
      - "3004:3004"
    volumes: 
      - ./micronode-event:/opt/app

  